spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: msh-service
          uri: http://localhost:8081
          predicates:
            - Path=/email/**
        - id: symon-portal
          uri: http://localhost:4976
          predicates:
            - Path=/portal/**
server:
  port: 8080
