spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: msh-service
          uri: http://localhost:8081
          predicates:
            - Path=/email/**
server:
  port: 8080
